services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Diamantor-G
      POSTGRES_DB: store-brain
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  storebrain-backend:
  build: ./storebrain-backend
  restart: always
  environment:
    NODE_ENV: production
    DATABASE_URL: "postgresql://postgres:Diamantor-G@db:5432/store-brain?schema=public"
    jwtSecretKey: HoFE0l2Hba0SgKK3lhyL/HjdA6/6IDqsfNtnupHFHaWXuNOc3nAHXlVam7msJNDX3eNPygSXK6ot3v780h6K/Q==
    jwtRefreshTokenKey: snfd8fZ9mBVSQUp0itECLax17wqrNVVTAppPROws+2x5BSW0iXXNwEBEoP70RSDigTKDWBxEfO32FSI8GvpSsQ==
    EMAIL_ID: no-reply@diamantor.fr
    EMAIL_PASS: Y@849080337560ow
    EMAIL_HOST: smtp.office365.com
    EMAIL_PORT: 587
    PRESTA_URL: https://www.diamantor.fr/api
    PRESTA_KEY: NjlZRkgxSTM3SUxBOEJZTkZHRVRQMkQ1WUZUSUFRR1I6
    NEST_DEBUG: "true"
  depends_on:
    - db
  ports:
    - "3010:3010"
    - "5555:5555"
  networks:
    - app-network

  storebrain-frontend:
    build:
      context: ./storebrain-frontend
      args:
        NEXTAUTH_URL: http://192.168.1.231:3000
        NEXTAUTH_URL_INTERNAL: http://192.168.1.231:3000
        AUTH_SECRET: 0lDqincx26d0HZ4onEvTeYO4vJegfa6xmpiqp7cupwk=
        AUTH_TRUST_HOST: "true"
        NEXT_PUBLIC_API_URL: http://storebrain-backend:3010/api/v1
        API_URL: http://storebrain-backend:3010/api/v1
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://storebrain-backend:3010/api/v1
      API_URL: http://storebrain-backend:3010/api/v1
      NEXTAUTH_URL: http://192.168.1.231:3000
      NEXTAUTH_URL_INTERNAL: http://192.168.1.231:3000
      AUTH_TRUST_HOST: "true"
      AUTH_SECRET: 0lDqincx26d0HZ4onEvTeYO4vJegfa6xmpiqp7cupwk=
    ports:
      - "3001:3000"
    depends_on:
      - storebrain-backend
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
