import { Grouping } from 'src/common/interfaces/analyse.interface';

const doigtGroupings: Grouping[] = [
  {
    department: 'OR',
    group: 'Doigt',
    family: null,
    stone: null,
    label: null,
    withStone: null,
    other: false,
    default: false,
    subGroupings: [
      //Solitaire
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Solitaire',
        stone: 'Diamant',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Solitaire',
        stone: 'Diamant Laboratoire (de synthèse)',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Solitaire',
        stone: 'Oxyde de zirconium',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Solitaire',
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Solitaire',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Alliance
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Alliances',
        stone: 'Diamant',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Alliances',
        stone: 'Diamant Laboratoire (de synthèse)',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Alliances',
        stone: 'Oxyde de zirconium',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Alliances',
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Alliances',
        stone: null,
        withStone: false,
        label: 'Tout OR',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Alliances',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Chevalière
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Chevalière',
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Chevalière',
        stone: null,
        withStone: false,
        label: 'Tout OR',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Chevalière',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Solitaire composition
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Solitaire composition',
        stone: 'Diamant',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Solitaire composition',
        stone: 'Diamant Laboratoire (de synthèse)',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Solitaire composition',
        stone: 'Oxyde de zirconium',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Solitaire composition',
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Solitaire composition',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Bague
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Bague',
        familyKeyword: 'Trilogie',
        stone: 'Diamant',
        withStone: null,
        label: 'Trilogie',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Bague',
        familyKeyword: 'Trilogie',
        stone: 'Diamant Laboratoire (de synthèse)',
        withStone: null,
        label: ' - Trilogie',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Bague',
        stone: 'Diamant',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Bague',
        stone: 'Diamant Laboratoire (de synthèse)',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Bague',
        stone: 'Oxyde de zirconium',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Bague',
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Bague',
        stone: null,
        withStone: false,
        label: 'Tout OR',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Doigt',
        family: 'Bague',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
    ],
  },
];

const couGroupings: Grouping[] = [
  {
    department: 'OR',
    group: 'Cou',
    family: null,
    stone: null,
    label: null,
    withStone: null,
    other: false,
    default: false,
    subGroupings: [
      //Collier
      {
        department: 'OR',
        group: 'Cou',
        family: 'Collier',
        stone: 'Diamant',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Cou',
        family: 'Collier',
        stone: 'Diamant Laboratoire (de synthèse)',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Cou',
        family: 'Collier',
        stone: 'Oxyde de zirconium',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Cou',
        family: 'Collier',
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Cou',
        family: 'Collier',
        stone: null,
        withStone: false,
        label: 'Tout OR',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Cou',
        family: 'Collier',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Chaine - Forçat
      {
        department: 'OR',
        group: 'Cou',
        family: 'Chaine',
        stone: null,
        withStone: null,
        label: 'Forçat',
        familyKeyword: 'Forçat',
        other: false,
        default: false,
      },
      //Chaine - Gourmette
      {
        department: 'OR',
        group: 'Cou',
        family: 'Chaine',
        stone: null,
        withStone: null,
        label: 'Gourmette',
        familyKeyword: 'Gourmette',
        other: false,
        default: false,
      },
      //Chaine
      {
        department: 'OR',
        group: 'Cou',
        family: 'Chaine',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
    ],
  }
];

export const groupings: Grouping[] = [
  //OR - DOIGT
  ...doigtGroupings,
  //OR - Cou
  ...couGroupings,  
  //OR - Poignet
  {
    department: 'OR',
    group: 'Poignet',
    family: null,
    stone: null,
    label: null,
    withStone: null,
    other: false,
    default: false,
    subGroupings: [
      //Bracelet
      {
        department: 'OR',
        group: 'Poignet',
        family: 'Bracelet',
        stone: 'Diamant',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Poignet',
        family: 'Bracelet',
        stone: 'Diamant Laboratoire (de synthèse)',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Poignet',
        family: 'Bracelet',
        stone: 'Oxyde de zirconium',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Poignet',
        family: 'Bracelet',
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Poignet',
        family: 'Bracelet',
        stone: null,
        withStone: false,
        label: 'Tout OR',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Poignet',
        family: 'Bracelet',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Identité
      {
        department: 'OR',
        group: 'Poignet',
        family: 'Identité',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Identité
      {
        department: 'OR',
        group: 'Poignet',
        family: 'Jonc',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
    ],
  },
  //OR - Oreilles
  {
    department: 'OR',
    group: 'Oreilles',
    family: null,
    stone: null,
    label: null,
    withStone: null,
    other: false,
    default: false,
    subGroupings: [
      //Boucles d'oreilles
      {
        department: 'OR',
        group: 'Oreilles',
        family: "Boucles d'oreilles",
        familyKeyword: 'Enfant',
        stone: null,
        withStone: null,
        label: 'Enfant',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Oreilles',
        family: "Boucles d'oreilles",
        stone: 'Diamant',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Oreilles',
        family: "Boucles d'oreilles",
        stone: 'Diamant Laboratoire (de synthèse)',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Oreilles',
        family: "Boucles d'oreilles",
        stone: 'Oxyde de zirconium',
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Oreilles',
        family: "Boucles d'oreilles",
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Oreilles',
        family: "Boucles d'oreilles",
        stone: null,
        withStone: false,
        label: 'Tout OR',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Oreilles',
        family: "Boucles d'oreilles",
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Créoles
      {
        department: 'OR',
        group: 'Oreilles',
        family: 'Créoles',
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Oreilles',
        family: 'Créoles',
        stone: null,
        withStone: false,
        label: 'Tout OR',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Oreilles',
        family: 'Créoles',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
    ],
  },
  //OR - Suspendu
  {
    department: 'OR',
    group: 'Suspendu',
    family: null,
    stone: null,
    label: null,
    withStone: null,
    other: false,
    default: false,
    subGroupings: [
      //Pendentif Religieux
      {
        department: 'OR',
        group: 'Suspendu',
        family: 'Pendentif Religieux',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Pendentif Zodiaque
      {
        department: 'OR',
        group: 'Suspendu',
        family: 'Pendentif Zodiaque',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Pendentif Initiale
      {
        department: 'OR',
        group: 'Suspendu',
        family: 'Pendentif Initiale',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Pendentif Regionaux
      {
        department: 'OR',
        group: 'Suspendu',
        family: 'Pendentif Regionaux',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Pendentif Laïque
      {
        department: 'OR',
        group: 'Suspendu',
        family: 'Pendentif Laïque',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Pendentif
      {
        department: 'OR',
        group: 'Suspendu',
        family: 'Pendentif',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
    ],
  },
  //OR - Piercing
  {
    department: 'OR',
    group: 'Piercing',
    family: null,
    stone: null,
    label: null,
    withStone: null,
    other: false,
    default: false,
    subGroupings: [
      //Piercing
      {
        department: 'OR',
        group: 'Piercing',
        family: 'Piercing',
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Piercing',
        family: 'Piercing',
        stone: null,
        withStone: false,
        label: 'Tout OR',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Piercing',
        family: 'Piercing',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Piercing Nombril
      {
        department: 'OR',
        group: 'Piercing',
        family: 'Piercing Nombril',
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Piercing',
        family: 'Piercing Nombril',
        stone: null,
        withStone: false,
        label: 'Tout OR',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Piercing',
        family: 'Piercing Nombril',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
      //Piercing Nez
      {
        department: 'OR',
        group: 'Piercing',
        family: 'Piercing Nez',
        stone: null,
        withStone: true,
        label: 'Empierré',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Piercing',
        family: 'Piercing Nez',
        stone: null,
        withStone: false,
        label: 'Tout OR',
        other: false,
        default: false,
      },
      {
        department: 'OR',
        group: 'Piercing',
        family: 'Piercing Nez',
        stone: null,
        withStone: null,
        label: null,
        other: false,
        default: false,
      },
    ],
  },
  // NE PAS TOUCHER
  //Default OR
  {
    department: 'OR',
    group: null,
    family: null,
    stone: null,
    label: 'Autres',
    withStone: null,
    other: false,
    default: true,
  },
];

export const detailGroupings: Grouping[] = [
  //Collier
  {
    department: 'OR',
    group: 'Cou',
    family: 'Collier',
    stone: 'Diamant',
    withStone: null,
    label: null,
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Cou',
    family: 'Collier',
    stone: 'Diamant Laboratoire (de synthèse)',
    other: false,
    withStone: null,
    label: null,
    default: false,
  },
  {
    department: 'OR',
    group: 'Cou',
    family: 'Collier',
    stone: 'Oxyde de zirconium',
    other: false,
    withStone: null,
    label: null,
    default: false,
  },
  {
    department: 'OR',
    group: 'Cou',
    family: 'Collier',
    stone: null,
    withStone: true,
    label: 'Empierré',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Cou',
    family: 'Collier',
    stone: null,
    withStone: false,
    label: 'Tout OR',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Cou',
    family: 'Collier',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Chaine
  {
    department: 'OR',
    group: 'Cou',
    family: 'Chaine',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Poignet
  //Bracelet
  {
    department: 'OR',
    group: 'Poignet',
    family: 'Bracelet',
    stone: 'Diamant',
    withStone: null,
    label: null,
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Poignet',
    family: 'Bracelet',
    stone: 'Diamant Laboratoire (de synthèse)',
    other: false,
    withStone: null,
    label: null,
    default: false,
  },
  {
    department: 'OR',
    group: 'Poignet',
    family: 'Bracelet',
    stone: 'Oxyde de zirconium',
    other: false,
    withStone: null,
    label: null,
    default: false,
  },
  {
    department: 'OR',
    group: 'Poignet',
    family: 'Bracelet',
    stone: null,
    withStone: true,
    label: 'Empierré',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Poignet',
    family: 'Bracelet',
    stone: null,
    withStone: false,
    label: 'Tout OR',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Poignet',
    family: 'Bracelet',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Identité
  {
    department: 'OR',
    group: 'Poignet',
    family: 'Identité',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Jonc
  {
    department: 'OR',
    group: 'Poignet',
    family: 'Jonc',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Doigt
  //Solitaire
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Solitaire',
    stone: 'Diamant',
    withStone: null,
    label: null,
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Solitaire',
    stone: 'Diamant Laboratoire (de synthèse)',
    other: false,
    withStone: null,
    label: null,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Solitaire',
    stone: 'Oxyde de zirconium',
    other: false,
    withStone: null,
    label: null,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Solitaire',
    stone: null,
    withStone: true,
    label: 'Empierré',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Solitaire',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Alliances
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Alliances',
    stone: 'Diamant',
    withStone: null,
    label: null,
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Alliances',
    stone: 'Diamant Laboratoire (de synthèse)',
    other: false,
    withStone: null,
    label: null,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Alliances',
    stone: 'Oxyde de zirconium',
    other: false,
    withStone: null,
    label: null,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Alliances',
    stone: null,
    withStone: true,
    label: 'Empierré',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Alliances',
    stone: null,
    withStone: false,
    label: 'Tout OR',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Alliances',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Chevaliere
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Chevalière',
    stone: null,
    withStone: true,
    label: 'Empierré',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Chevalière',
    stone: null,
    withStone: false,
    label: 'Tout OR',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Chevalière',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Solitaire composition
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Solitaire composition',
    stone: 'Diamant',
    withStone: null,
    label: null,
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Solitaire composition',
    stone: 'Diamant Laboratoire (de synthèse)',
    other: false,
    withStone: null,
    label: null,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Solitaire composition',
    stone: 'Oxyde de zirconium',
    other: false,
    withStone: null,
    label: null,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Solitaire composition',
    stone: null,
    withStone: true,
    label: 'Empierré',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Doigt',
    family: 'Solitaire composition',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Oreilles
  //Créoles
  {
    department: 'OR',
    group: 'Oreilles',
    family: 'Créoles',
    stone: null,
    withStone: true,
    label: 'Empierré',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Oreilles',
    family: 'Créoles',
    stone: null,
    withStone: false,
    label: 'Tout OR',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Oreilles',
    family: 'Créoles',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Suspendu
  {
    department: 'OR',
    group: 'Suspendu',
    family: 'Pendentif Religieux',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  {
    department: 'OR',
    group: 'Suspendu',
    family: 'Pendentif Zodiaque',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  {
    department: 'OR',
    group: 'Suspendu',
    family: 'Pendentif Initiale',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  {
    department: 'OR',
    group: 'Suspendu',
    family: 'Pendentif Regionaux',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  {
    department: 'OR',
    group: 'Suspendu',
    family: 'Pendentif Laïque',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Piercing
  //Piercing
  {
    department: 'OR',
    group: 'Piercing',
    family: 'Piercing',
    stone: null,
    withStone: true,
    label: 'Empierré',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Piercing',
    family: 'Piercing',
    stone: null,
    withStone: false,
    label: 'Tout OR',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Piercing',
    family: 'Piercing',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Piercing Nez
  {
    department: 'OR',
    group: 'Piercing',
    family: 'Piercing Nez',
    stone: null,
    withStone: true,
    label: 'Empierré',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Piercing',
    family: 'Piercing Nez',
    stone: null,
    withStone: false,
    label: 'Tout OR',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Piercing',
    family: 'Piercing Nez',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //Piercing Nombril
  {
    department: 'OR',
    group: 'Piercing',
    family: 'Piercing Nombril',
    stone: null,
    withStone: true,
    label: 'Empierré',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Piercing',
    family: 'Piercing Nombril',
    stone: null,
    withStone: false,
    label: 'Tout OR',
    other: false,
    default: false,
  },
  {
    department: 'OR',
    group: 'Piercing',
    family: 'Piercing Nombril',
    stone: null,
    withStone: null,
    label: null,
    other: true,
    default: false,
  },
  //DEFAULT
  {
    department: null,
    group: null,
    family: null,
    stone: null,
    withStone: null,
    label: null,
    other: false,
    default: true,
  },
];
